// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client.proto

package ru.itmo.java.message;

public final class Client {
  private Client() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_itmo_java_message_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_itmo_java_message_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Client.proto\022\024ru.itmo.java.message\"\026\n\007" +
      "Request\022\013\n\003arr\030\001 \003(\005\"\033\n\010Response\022\017\n\007sort" +
      "Arr\030\001 \003(\005B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_itmo_java_message_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_itmo_java_message_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_Request_descriptor,
        new java.lang.String[] { "Arr", });
    internal_static_ru_itmo_java_message_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_itmo_java_message_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_itmo_java_message_Response_descriptor,
        new java.lang.String[] { "SortArr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
