// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client.proto

package ru.itmo.java.message;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 arr = 1;</code>
   * @return A list containing the arr.
   */
  java.util.List<java.lang.Integer> getArrList();
  /**
   * <code>repeated int32 arr = 1;</code>
   * @return The count of arr.
   */
  int getArrCount();
  /**
   * <code>repeated int32 arr = 1;</code>
   * @param index The index of the element to return.
   * @return The arr at the given index.
   */
  int getArr(int index);
}
