// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client.proto

package ru.itmo.java.message;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.itmo.java.message.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 sortArr = 1;</code>
   * @return A list containing the sortArr.
   */
  java.util.List<java.lang.Integer> getSortArrList();
  /**
   * <code>repeated int32 sortArr = 1;</code>
   * @return The count of sortArr.
   */
  int getSortArrCount();
  /**
   * <code>repeated int32 sortArr = 1;</code>
   * @param index The index of the element to return.
   * @return The sortArr at the given index.
   */
  int getSortArr(int index);
}
